name: Build and Test

on:
  push:
    branches: ["lti-integration"]
  pull_request:
    branches: ["lti-integraion"]

jobs:
  cache-and-install:
    runs-on: [self-hosted, ec2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit tests
        run: echo "Bypassing tests because they are not implemented yet."